import './globals.css'
import type { Metadata } from 'next'
import { Inter, Poppins, Raleway } from 'next/font/google'
import Header from './components/Header'
import TopContact from './components/TopContact';

const inter = Inter({ subsets: ['latin'], variable: "--inter" })
const poppins = Poppins({ subsets: ['latin'], variable: "--poppins", weight: ["400", "600", "700"], style: ["italic"] })
const raleway = Raleway({ subsets: ['latin'], variable: "--raleway", weight: ["400", "600", "700"], style: ["italic"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={(inter.variable, poppins.variable, raleway.variable)}>
        <TopContact />
        <Header />
        {children}
      </body>
    </html>
  )
}
